name: dishmark
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  path_provider: ^2.1.0
  amap_flutter_map_plus: ^3.1.1
  amap_flutter_base_plus: ^3.1.0
  permission_handler: ^11.3.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  isar_generator: ^3.1.0
  build_runner: ^2.4.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpg"

flutter:
  uses-material-design: true
