name: dishmark
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1+2

environment:
  sdk: ">=3.8.0 <4.0.0"

fluwx:
  app_id: 'wxad43d21e6da50817' # TODO: replace with your real WeChat app id (starts with wx).
  debug_logging: true # Logging in debug mode.
  android:
#    interrupt_wx_request: true # Defaults to true.
#    flutter_activity: 'MainActivity' # Defaults to app's launcher
  ios:
    universal_link: https://dishmark.loopshen.top/
    no_pay: true # Set to true to disable payment.
    scene_delegate: false # Use AppDelegate callback path for WeChat universal link.
#    ignore_security: true # Set to true to disable security seetings.

dependencies:
  flutter:
    sdk: flutter
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  path_provider: ^2.1.0
  image_picker: ^1.1.2
  amap_flutter_map_plus: ^3.1.1
  amap_flutter_base_plus: ^3.1.0
  permission_handler: ^11.3.1
  flutter_launcher_icons: ^0.14.4
  share_plus: ^10.1.2
  fluwx: ^5.7.5
  flutter_svg: ^2.2.1
  geocoding: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  isar_generator: ^3.1.0
  build_runner: ^2.4.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/create_button.svg
